### ISSUE TITLE
Feature request: reuse existing textarea instead of creating new one

### ISSUE THREAD

**Issue by MarkusNaeher** [fatihege/downarea#1]
Hi,
I just discovered your library, and it looks like it's the only one I can use at all :-) because all the others have loads of dependencies which I don't want to or even can't have (like angular). I need something that's embeddable into my JSF (Java Server Faces) project (therefore angular and the like are conflicting technologies). When I create a textarea in JSF, it already has some specific properties, attached JavaScript and so on that is all needed to work properly inside the JSF environment. When this is thrown away, it does not work anymore.

I think the easiest way would be to reuse the existing textarea instead of creating new one. This would make your lib embeddable not only in JSF but probably also other frameworks. Yes, this would make some of the parameters (like initial text) obsolete but I don't think that's a problem.

**Comment by fatihege** [comment]
I will add the feature you want to the library at a suitable time and publish it. Thank you for the suggestion. :)

**Comment by fatihege** [comment]
The feature you want has been added and the new version has been released. Check the version [1.3.0](https://github.com/fatihege/downarea/tree/v1.3.0).
